name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: configure
      # Brew doesn't symlink openssl into system directories so we have to tell cmake where it is
      run: export OPENSSL_ROOT_DIR=`brew --prefix openssl@3` && cmake .
    - name: make
      run: make
    
